version: "3.9"

services:
  web:
    build:
      context: ./ui/
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./ui/.env
    depends_on:
      - api
    profiles: ["web"]
  preview:
    build:
      context: ./ui/
      dockerfile: preview.Dockerfile
    command: yarn serve
    ports:
      - 4173:4173
    volumes:
      - ./ui:/app
      - /app/node_modules/
    env_file:
      - ./ui/.env
    depends_on:
      - api
    profiles: ["preview"]
  api:
    build:
      context: ./api
    command: poetry run gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --reload --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - secrets/api.env
    volumes:
      - ./api:/app
      - /app/.venv/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail localhost:8000/health_check || exit 1
  db:
    build: ./postgis-h3
      # context: ./postgis-h3
      # dockerfile: arm64.Dockerfile
    shm_size: 2gb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - secrets/db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    env_file:
      - ./secrets/pgweb.env
    depends_on:
      db:
        condition: service_healthy
volumes:
  pg_data:
