version: "3.9"

services:
  web:
    build:
      context: ./ui/
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./ui/.env
    depends_on:
      - api
    profiles: [ "web" ]
  preview:
    build:
      context: ./ui/
      dockerfile: preview.Dockerfile
    command: yarn serve
    ports:
      - 4173:4173
    volumes:
      - ./ui:/app
      - /app/node_modules/
    env_file:
      - ./ui/.env
    depends_on:
      - api
    profiles: [ "preview" ]
  api:
    build:
      context: ./api
    # command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    command: poetry run gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --reload --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - secrets/api.env
    volumes:
      - ./api:/app
      - /app/.venv/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail localhost:8000/health_check || exit 1
  db:
    build:
      context: ./postgis-h3
      # comment out the following for better performance on an ARM-based device (e.g. M1/M2 MacBooks)
      # dockerfile: arm64.Dockerfile
    shm_size: 2gb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - secrets/db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    env_file:
      - ./secrets/pgweb.env
    depends_on:
      db:
        condition: service_healthy
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    restart: always
    container_name: worldex-es01
    environment:
      - node.name=es01
      - cluster.name=worldex-es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - _volumes/elasticsearch/data/01:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    restart: always
    container_name: worldex-es02
    environment:
      - node.name=es02
      - cluster.name=worldex-es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - _volumes/elasticsearch/data/02:/usr/share/elasticsearch/data
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    restart: always
    container_name: worldex-es03
    environment:
      - node.name=es03
      - cluster.name=worldex-es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - _volumes/elasticsearch/data/03:/usr/share/elasticsearch/data

volumes:
  pg_data:
