version: "3.9"
services:
  ui:
    build:
      context: ./ui/
      dockerfile: dev.Dockerfile
    command: yarn start
    ports:
      - 5173:5173
    volumes:
      - ./ui:/app
    env_file:
      - ./ui/.env
    depends_on:
      - api
  api:
    build:
      context: ./api
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail localhost:8000/health_check || exit 1
  api-venv:
    build:
      context: ./api
    volumes:
      - ./api:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    depends_on:
      api:
        condition: service_healthy
    command: chown -R $USER:$USER .venv && echo "chowned .venv"
  db:
    build: ./postgis-h3
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=worldex
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://worldex:postgres@db/worldex?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
volumes:
  pg_data:
  poetry_venv:
