version: "3.8"
services:
  ui:
    build:
      context: ./ui/
      dockerfile: dev.Dockerfile
    command: yarn start
    ports:
      - 5173:5173
    volumes:
      - ./ui:/app
    env_file:
      - ./ui/.env
    depends_on:
      - api
  api:
    build:
      context: ./api
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    depends_on:
      - db
    healthcheck:
      test: curl --fail localhost:8000/health_check || exit 1
  api-venv:
    build:
      context: ./api
    volumes:
      - ./api:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    depends_on:
      api:
        condition: service_healthy
    # restart: "no"
    command: bash -c 'while !<.venv/; do sleep1; done; chown -R $USER:$USER .venv && echo "chowned .venv"'
  db:
    build: ./postgis-h3
    volumes:
      - pg_data:/var/lib/postresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=worldex
      - POSTGRES_PASSWORD=postgres
volumes:
  pg_data:
