services:
  api:
    build:
      context: ./api
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code
  db:
    build: ./postgis-h3
    container_name: db
    volumes:
      - ./data/db:/var/lib/postresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=worldex
      - POSTGRES_PASSWORD=postgres