[tool.poetry]
name = "worldex"
version = "0.0.1"
description = ""
authors = ["Aivin V. Solatorio <avsolatorio@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry_bumpversion.file."worldex/__init__.py"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
