steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/worldex-repo/cors-anywhere:0.4.4 .
  automapSubstitutions: true
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/worldex-repo/cors-anywhere:0.4.4'