site_name: worldex
nav:
  - Getting Started:
      - Introduction: index.md
      - Installation: installation.md
      - Quick Start: quick_start.ipynb
      - Dataset Providers: dataset_providers.md
      - Metadata Schema: quick_start.ipynb
  - Examples:
      - Generic Vector Data: notebooks/index_generic_vector.ipynb
      - HDX: notebooks/index_hdx.ipynb
      - WorldPop: notebooks/index_worldpop.ipynb
      - EnergyData: notebooks/index_energydata.ipynb
      - Protected Planet: notebooks/index_protectedplanet.ipynb
      - UNHCR: notebooks/index_unhcr.ipynb
      - World Bank Catalog: notebooks/index_worldbankcatalog.ipynb
      - Building a custom provider: notebooks/custom_provider.ipynb
theme:
  name: material
  features:
    - navigation.expand
    - navigation.path
plugins:
  - mkdocs-jupyter
