steps:
# Bundle application
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']
  dir: 'ui/'
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: 'bash'
#   args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
#   dir: 'ui/'
timeout: '1600s'